#!/usr/bin/env bash
# Script installs nginx on server.
sudo apt-get -y update
sudo apt-get install -y nginx
echo "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;
}" > /etc/nginx/sites-available/default
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo service nginx restart
