#!/usr/bin/env bash
# Install and configure load balancer

load_balance_config="\
frontend welcomeClient
        bind *:80
        mode http
        default_backend twoWebServers

backend twoWebServers
        balance roundrobin
        server 470159-web-01 54.144.151.193
        server 470159-web-02 100.26.253.7
"

sudo apt-get -y update
sudo apt-get -y upgrade

sudo apt-get -y install haproxy
echo "$load_balance_config" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo service haproxy restart
