#!/usr/bin/env bash

#a Bash script that displays the time for 12 hours and 59 minutes

hours=0


while (( hours < 13 )); do
    echo "Hour: $hours"
    ((hours++))
    ((minutes=1))
    while ((minutes < 60)); do
        echo $minutes
        ((minutes++))
    done
done
