#!/usr/bin/env bash
ssh-keygen -b 4096 -f ~/.ssh/school -N 'betty'

#-f: This option allows you to specify the filename of the key file. In the context of your script, -f ~/.ssh/school tells ssh-keygen to create the key pair in the ~/.ssh/ directory with the name school.
#-N: This option is used to set the passphrase for the key. In the context of your script, -N 'betty' sets the passphrase for the key to betty.
